name: tests

on:
  push:
    branches:
      - 'develop'
      - 'release/**'

jobs:
  Tests:
    name: Tests
    runs-on: macOS-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
      PROJECT: VirgilSDK.xcodeproj
    strategy:
      matrix:
        include:
          - destination: "OS=17.0,name=iPhone 14"
            prefix: "iOS"
            test: "1"
          - destination: "arch=x86_64"
            prefix: "macOS"
            test: "1"
          - destination: "OS=17.0,name=Apple TV"
            prefix: "tvOS"
            test: "1"
          - destination: "OS=10.0,name=Apple Watch Series 7 - 45mm"
            prefix: "watchOS"
            test: "0"
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt tests config
        run: ./CI/decrypt-config.sh
        env:
            ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
            ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
      - name: Run ${{ matrix.prefix }} Tests
        uses: nick-fields/retry@v2
        with:
          max_attempts: 20
          timeout_minutes: 30
          retry_on: error
          command: |
            SCHEME="VirgilSDK ${{ matrix.prefix }}"

              if [ "${{ matrix.test }}" == "1" ]; then
                  # Build & Test
                  xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -destination "${{ matrix.destination }}" -configuration Debug test | xcpretty;
              else
                  # Build Only
                  xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -destination "${{ matrix.destination }}" -configuration Release clean build | xcpretty;
              fi
  SPM:
    runs-on: macOS-13
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt tests config
        run: ./CI/decrypt-config.sh
        env:
            ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
            ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
      - name: SPM test
        run: |
            brew install coreutils # install 'timeout' utility
            swift --version
            # fix for Swift Package Manager when it fails to download binary targets
            timeout 5m bash -c 'until swift build; do rm -fr .build && sleep 10; done'
            swift test
